import json
import unittest

import numpy as np
import pandas as pd

from report_g0_headroom import (
    design_aware_profile,
    joint_counts_for_log,
    mask_histogram,
    metric_summary,
    observation_model,
    total_variation,
)
from walks import build_index


class G0HeadroomTests(unittest.TestCase):
    def test_mask_histogram_collapses_n_but_keeps_masks(self):
        raw = json.dumps({"1,01": 2, "2,01": 3, "2,03": 4})
        result = mask_histogram(raw)
        self.assertEqual(result[0], 0)
        self.assertEqual(result[1], 5)
        self.assertEqual(result[3], 4)

    def test_joint_counts_include_unobserved_population_dyads(self):
        events = pd.DataFrame({
            "u": [0, 0, 1], "v": [1, 1, 2], "t": [0.1, 0.3, 0.7],
        })
        idx = build_index(events, T=1.0, W=5)
        log = pd.DataFrame({
            "kind": [0, 1], "u": [-1, 0], "v": [-1, 1],
            "t": [np.nan, 0.1], "node": [0, 1], "dt": [np.nan, 0.1],
        })
        counts = joint_counts_for_log(log, idx, budget=2, W=5)
        # (0,1) is active in two windows and observed in mask 00001;
        # (1,2) is a K=1 population dyad and remains at mask zero.
        self.assertEqual(counts[2, 0b00001], 1)
        self.assertEqual(counts[1, 0], 1)
        self.assertEqual(counts.sum(), 2)

    def test_observation_model_is_group_balanced_and_excludable(self):
        rows = []
        for group, zero, one in [("large", 90, 10), ("small", 1, 9)]:
            for arm in ("time_agnostic_t", "time_respecting", "recent_history_k20"):
                for k in range(1, 6):
                    for mask, count in [(0, zero), (1, one)]:
                        rows.append({"group_id": group, "arm": arm, "K": k,
                                     "mask": mask, "count": count})
        counts = pd.DataFrame(rows)
        q = observation_model(counts)["time_agnostic_t"]
        self.assertAlmostEqual(q[1, 1], 0.5, places=12)
        q_excluded = observation_model(counts, ["large"])["time_agnostic_t"]
        self.assertAlmostEqual(q_excluded[1, 1], 0.9, places=12)

    def test_design_aware_profile_divides_out_inclusion(self):
        q = np.zeros((6, 32), dtype=float)
        # K=1 is included with probability .2 and emits mask 1.
        q[1, 0], q[1, 1] = 0.8, 0.2
        # K=2 is included with probability .8 and emits mask 3.
        q[2, 0], q[2, 3] = 0.2, 0.8
        # Remaining states are irrelevant but need a valid observation model.
        for k in (3, 4, 5):
            q[k, 0], q[k, (1 << k) - 1] = 0.5, 0.5
        observed = np.zeros(32)
        # Generated by population pi=(.75,.25,0,0,0): expected included
        # masses are .15 and .20, hence 150 vs 200 observations.
        observed[1], observed[3] = 150, 200
        profile = design_aware_profile(observed, q)
        self.assertAlmostEqual(profile[0], 0.25, places=3)
        self.assertAlmostEqual(profile[1], 0.0, places=3)

    def test_group_macro_metrics_are_not_pooled_metrics(self):
        frame = pd.DataFrame({
            "group_id": ["a", "b", "b", "b"],
            "rho_W5_k2": [0, 0, 0, 0], "rho_W5_k3": [0, 0, 0, 0],
            "rho_W5_k4": [0, 0, 0, 0], "rho_W5_k5": [0, 0, 0, 0],
            "p2": [1, 0, 0, 0], "p3": [1, 0, 0, 0],
            "p4": [1, 0, 0, 0], "p5": [1, 0, 0, 0],
        })
        result = metric_summary(frame, ["p2", "p3", "p4", "p5"])
        self.assertAlmostEqual(result["profile_mae"], 0.5)
        self.assertAlmostEqual(result["pooled_profile_mae"], 0.25)

    def test_total_variation(self):
        self.assertEqual(total_variation([1, 0], [1, 0]), 0.0)
        self.assertEqual(total_variation([1, 0], [0, 1]), 1.0)


if __name__ == "__main__":
    unittest.main()
