#!/usr/bin/env python3
"""Evaluate the small set of design-aware additions to benchmark v2.

Outputs are supplementary and never overwrite the frozen main evaluation.
The script uses existing case shards for:

* model-assisted Hansen--Hurwitz (``time_agnostic_t`` only);
* Chao1/Good--Turing discovery diagnostics (not scored as rho estimators);
* monotone PAVA projections of analytical persistence profiles;
* optionally one ExtraTrees/combined profile model plus its projection.

Oracle-label rows are included when cases were regenerated by the current
``benchmark_features.py``; old frozen shards simply omit those diagnostics.
"""

import argparse
import glob
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupKFold

from design_baselines import (
    discovery_diagnostics,
    model_assisted_hh_from_json,
    parse_nmask_hist,
    project_profile_decreasing,
)
from evaluate_benchmark import (
    _fit_models,
    _prediction_records,
    compute_metrics,
    load_evaluation_config,
    make_rankings,
    read_cases,
)

RHO_TARGETS = [f"rho_W5_k{k}" for k in range(2, 6)]


def _long_predictions(cases, name, columns, protocol="design_diagnostic"):
    out = []
    for target, column in zip(RHO_TARGETS, columns):
        if column not in cases:
            return []
        out.append(_prediction_records(
            cases, target, name, "analytical", cases[column].to_numpy(float),
            fold="none", protocol=protocol))
    return out


def add_shape_projection(part, suffix="_shape"):
    """Return projected copies for models having all four rho predictions."""
    keys = ["case_id", "model", "input", "fold", "protocol"]
    rho = part[part["target"].isin(RHO_TARGETS)]
    if rho.empty:
        return pd.DataFrame()
    wide = rho.pivot_table(index=keys, columns="target", values="prediction",
                           aggfunc="first").dropna(subset=RHO_TARGETS)
    if wide.empty:
        return pd.DataFrame()
    projected = np.vstack([
        project_profile_decreasing(row)
        for row in wide[RHO_TARGETS].to_numpy(float)
    ])
    lookup = {
        (*idx, target): projected[i, j]
        for i, idx in enumerate(wide.index)
        for j, target in enumerate(RHO_TARGETS)
    }
    rows = []
    for _, r in rho.iterrows():
        key = tuple(r[k] for k in keys) + (r["target"],)
        if key not in lookup:
            continue
        q = r.copy()
        q["model"] = str(q["model"]) + suffix
        q["prediction"] = lookup[key]
        rows.append(q)
    return pd.DataFrame(rows)


def design_records(cases):
    records = []
    for estimator in ("plugin", "occ_mle", "mask_mle"):
        cols = [f"est__{estimator}_rho_k{k}" for k in range(2, 6)]
        records += _long_predictions(cases, estimator, cols)

    static = cases[cases["strategy"] == "time_agnostic_t"].copy()
    hh_values = {k: [] for k in range(2, 6)}
    diag_rows = []
    for _, row in static.iterrows():
        raw = row["input__nmask_exact_json"]
        hh = model_assisted_hh_from_json(raw)
        for k in range(2, 6):
            hh_values[k].append(hh.get(f"rho_k{k}", np.nan))
        n, _, counts = parse_nmask_hist(raw)
        diag_rows.append({
            "case_id": row["case_id"],
            **discovery_diagnostics(n, counts),
        })
    for k in range(2, 6):
        static[f"est__hh_mask_rho_k{k}"] = hh_values[k]
    records += _long_predictions(
        static, "hh_mask_stationary",
        [f"est__hh_mask_rho_k{k}" for k in range(2, 6)])

    oracle_specs = {
        "oracle_seen_label": [f"oracle__seen_label_rho_k{k}" for k in range(2, 6)],
        "oracle_hh_both": [f"oracle__hh_label_rho_k{k}" for k in range(2, 6)],
    }
    for name, cols in oracle_specs.items():
        records += _long_predictions(static, name, cols)
    return records, pd.DataFrame(diag_rows)


def extra_trees_records(cases, folds, jobs):
    records = []
    for strategy in sorted(cases["strategy"].unique()):
        x = cases[cases["strategy"] == strategy].reset_index(drop=True)
        groups = x["group_id"].astype(str).to_numpy()
        if len(np.unique(groups)) < 2:
            continue
        split = GroupKFold(min(folds, len(np.unique(groups))))
        y = x[RHO_TARGETS].to_numpy(float)
        for fold, (tr, te) in enumerate(split.split(x, y, groups)):
            records += _fit_models(
                x.iloc[tr], x.iloc[te], RHO_TARGETS, ["combined"],
                ["extra_trees"], jobs, model_suffix="_profile",
                fold=str(fold), protocol="group_kfold_profile")
            print(f"[ExtraTrees profile {strategy}] fold {fold + 1}", flush=True)
    return records


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="config/benchmark_v21.yaml")
    ap.add_argument("--preset", default="v2")
    ap.add_argument("--cases", nargs="+",
                    default=["results/benchmark_v2/results/cases_shard_*.csv.gz"])
    ap.add_argument("--out-dir", default="results/benchmark_v2/design_baselines")
    ap.add_argument("--fit-extra-trees", action="store_true")
    ap.add_argument("--folds", type=int, default=5)
    ap.add_argument("--jobs", type=int, default=-1)
    ap.add_argument("--strategies", default=None,
                    help="optional comma-separated subset (for smoke runs)")
    ap.add_argument("--max-cases", type=int, default=0,
                    help="optional debug limit after strategy filtering")
    args = ap.parse_args()

    cases, paths = read_cases(args.cases)
    if args.strategies:
        keep = set(args.strategies.split(","))
        cases = cases[cases["strategy"].isin(keep)].copy()
    if args.max_cases:
        cases = cases.head(args.max_cases).copy()
    print(f"{len(cases)} cases from {len(paths)} shard(s)", flush=True)

    records, discovery = design_records(cases)
    if args.fit_extra_trees:
        records += extra_trees_records(cases, args.folds, args.jobs)
    base = pd.concat(records, ignore_index=True)
    shaped = add_shape_projection(base)
    predictions = pd.concat([base, shaped], ignore_index=True)

    cfg = load_evaluation_config(args.config, args.preset)
    metrics = compute_metrics(predictions, cfg)
    rankings = make_rankings(metrics)
    out = Path(args.out_dir)
    out.mkdir(parents=True, exist_ok=True)
    predictions.to_csv(out / "predictions.csv.gz", index=False,
                       compression="gzip")
    discovery.to_csv(out / "discovery_diagnostics.csv.gz", index=False,
                     compression="gzip")
    metrics.to_csv(out / "metrics.csv", index=False)
    rankings.to_csv(out / "rankings.csv", index=False)

    headline = metrics[
        (metrics["target"] == "rho_W5_k2") &
        (metrics["slice_type"] == "overall")
    ].sort_values(["strategy", "protocol", "mae_group_macro"])
    cols = ["strategy", "model", "protocol", "n", "mae",
            "mae_group_macro", "mae_worst_group", "bias"]
    text = [
        "# Design-aware baseline results", "",
        "HH rows are reported only for `time_agnostic_t`; temporal-walk "
        "propensities are not treated as known.", "",
        headline[cols].to_markdown(index=False, floatfmt=".4f"), "",
    ]
    (out / "SUMMARY.md").write_text("\n".join(text))
    print(f"wrote {out}", flush=True)


if __name__ == "__main__":
    main()
